version: '3.4'
services:
  frontendserver:
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/frontendserver/Dockerfile
      network: host
    volumes:
      - ./certificates:/certificates/
    restart: always
    network_mode: host
    env_file: .env
  pvserver:
    environment:
      - DATABASE1=127.0.0.1:27017
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/pvserver/Dockerfile
    restart: always
    network_mode: host
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - ./certificates:/certificates/
      - ./users:/pvServer/userAuthentication/users

  unsecurestylguidepvserver:
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/pvserver/Dockerfile
    restart: always
    network_mode: host
    env_file: .env
    environment:
          - REACT_APP_PyEpicsServerPORT=5001
          - REACT_APP_EnableLogin=false
    volumes:
          - ./certificates:/certificates/

  demoioc:
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/demoioc/Dockerfile
    tty: true
    stdin_open: true
    restart: always
    network_mode: host
  styleguideserver:
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/styleguideserver/Dockerfile
    volumes:
      - ./certificates:/certificates/
    restart: always
    network_mode: host
    env_file: .env
    environment:
            - REACT_APP_PyEpicsServerPORT=5001
            - REACT_APP_EnableLogin=false
  loadsavedb:
    env_file: .env
    image: 'mongo'
    container_name: 'loadsavedb-container'
    volumes:
      - ./db:/data/db/
    ports:
      - 27017:27017
      - 27018:27018
      - 27109:27109