version: '3.2'
services:
  initializedb:
    env_file: .env
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/loadSaveDbInit/Dockerfile
    tty: true
    stdin_open: true
    #depends_on:
    #  - loadsavedb


