version: '3.2'
services:
  frontendserverdev:
    env_file: .env
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/frontendserverDev/Dockerfile
    volumes:
      - ./certificates:/certificates/
      - ./ReactApp/package.json:/frontendserverAppDev/package.json
      - ./ReactApp/src:/frontendserverAppDev/src
      - ./ReactApp/public:/frontendserverAppDev/public
    restart: always
    network_mode: host
  pvserver:
    env_file: .env
    environment:
      - DATABASE1=127.0.0.1:27017
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/pvserver/Dockerfile
    restart: always
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - ./certificates:/certificates/
      - ./users:/pvServer/userAuthentication/users
  unsecurestylguidepvserver:
    env_file: .env
    environment:
          - REACT_APP_PyEpicsServerPORT=5001
          - REACT_APP_EnableLogin=false

    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/pvserver/Dockerfile
    restart: always
    network_mode: host
    volumes:
      - ./certificates:/certificates/
  demoioc:
    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/demoioc/Dockerfile
    tty: true
    stdin_open: true
    restart: always
    network_mode: host
  styleguideserver:
    env_file: .env
    environment:
            - REACT_APP_PyEpicsServerPORT=5001
            - REACT_APP_EnableLogin=false

    build:
      context: ./
      args: # Environment variables available at build-time
                - http_proxy
                - https_proxy
                - no_proxy
      dockerfile: docker/styleguideserver/Dockerfile
    restart: always
    network_mode: host
    volumes:
      - ./certificates:/certificates/
  
  loadsavedb:
    env_file: .env
    image: 'mongo'
    container_name: 'loadsavedb-container'
    volumes:
      - ./db:/data/db/
    ports:
      - 27017:27017
      - 27018:27018
      - 27109:27109
  # initializedb:
  #   env_file: .env
  #   build:
  #     context: ./
  #     args: # Environment variables available at build-time
  #               - http_proxy
  #               - https_proxy
  #               - no_proxy
  #     dockerfile: docker/loadSaveDbInit/Dockerfile
  #   tty: true
  #   stdin_open: true
  #   depends_on:
  #     - loadsavedb


