version: "3.1"

services:
  alarmhandlerserver:
    build:
      context: ./
      dockerfile: docker/alarmHandlerServer/Dockerfile
    hostname: alarmhandlerserver
    restart: always
    network_mode: "host"
    stdin_open: true
    tty: true
    env_file:
      - alarmHandler.env